### ISSUE TITLE
can't get perfectlib to compile on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by edwardvalentini** [PerfectlySoft/Perfect#159]
I'm using ubuntu 14.04 LTS and up to this commit in Perfect `c6f0826`.
I'm also using `DEVELOPMENT-SNAPSHOT-2016-03-24-a`, but I get the following when trying to build Perfectlib

I have libcurl4-openssl-dev installed... and ldconfig shows that the curl libs are linked... 

```
$ swift build
Compiling Swift Module 'PerfectLib' (36 sources)
/home/vagrant/PerfectStarter/PerfectLib/Sources/PerfectLib/cURL.swift:87:13: error: use of unresolved identifier 'CURLOPT_HEADERDATA'
                setOption(CURLOPT_HEADERDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~~~
/home/vagrant/PerfectStarter/PerfectLib/Sources/PerfectLib/cURL.swift:88:13: error: use of unresolved identifier 'CURLOPT_WRITEDATA'
                setOption(CURLOPT_WRITEDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~~
/home/vagrant/PerfectStarter/PerfectLib/Sources/PerfectLib/cURL.swift:89:13: error: use of unresolved identifier 'CURLOPT_READDATA'
                setOption(CURLOPT_READDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/vagrant/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-03-24-a/usr/bin/swift-build-tool -f /home/vagrant/PerfectStarter/PerfectLib/.build/debug.yaml default
```

**Comment by ambientlight** [comment]
Please go to the cURL.swift in Sources/ and change '#if Ubuntu_14_04' to '#if os(Linux)

If you want to compile PerfectServer from it, you will need to fork Perfect, make a change, push it back and also make a newer tag for it. Then you would need to replace the PerfectLib dependency git URL and Version in Package.swift in PerfectServer

**Comment by edwardvalentini** [comment]
thanks that worked
